### ISSUE TITLE
notifications of unconfirmed transactions with sockect + nem-sdk not work ( i test in mainnet and testnet)

### ISSUE THREAD

**Issue by neetogami** [QuantumMechanics/NEM-sdk#43]
I subscribed to the channel to listen to unconfirmed transactions using the sockets of the library but they did not notify me when there are new unconfirmed transactions. I noticed the problem because the bots that sign a multi-signature transaction using their sockets no longer works.
Dont Work
nem.com.websockets.subscribe.account.transactions.unconfirmed(connector, function(res) {
            // Set time
            date = new Date();
            // Show event
            console.log(date.toLocaleString()+': Received unconfirmed transaction');
            // Show data
            console.log(date.toLocaleString()+': ' + JSON.stringify(res));
});
please check this

**Comment by csleary** [comment]
Yep, I seem to be having the same problem. Can't get the confirmed/unconfirmed transactions to come through on the mainnet (but the confirmed txs websocket seems to work on the testnet node 23.228.67.85 -- still no unconfirmed txs though).

**Comment by csleary** [comment]
Not sure what my problem was, but it could be an issue with sockjs. I worked around this by implementing stomp with native websockets rather than with sockjs, and it seems to work just fine now.

@neetogami -- Let me know if you'd like any help doing the same as I've done; I'd be happy to help out. 🙂

**Comment by neetogami** [comment]
can you publish the code that solves the problem to review it?

**Comment by csleary** [comment]
Gladly. Using stomp.js directly with a websocket boils down to this:

`import Stomp from 'stompjs';`

`url = ws://YOURNODE:7779/w/messages/websocket;`
`const socket = new WebSocket(url);`
`const client = Stomp.over(socket);`
`client.debug = undefined; // Comment this out to receive helpful info to debug the stomp connection.`

That sets up your stomp client to use a websocket rather than sockjs, then you call its connect function:

`client.connect({}, clientSuccess, clientError);`

Note the two callbacks for a successful connection and error respectively. We're sending an empty object  as the first argument as we don't need authentication or any extra headers. In the `clientSuccess` function, you'd set up your subscriptions, which might look like this:

`this.client.subscribe("/unconfirmed/ADDRESS", data => {`
`const res = JSON.parse(data.body);`
`console.log(res); // Play with the returned objects here.`
`});`

`this.client.subscribe("/transactions/ADDRESS", data => {`
`const res = JSON.parse(data.body);`
`console.log(res);`
`});`

This will subscribe to the unconfirmed and confirmed messages. Endpoints for other messages/subscriptions can be pulled from the [websockets source files](https://github.com/QuantumMechanics/NEM-sdk/tree/master/src/com/websockets).

In the `clientError` callback you might have a reconnection timeout and error message handling.

The [Stomp docs](http://jmesnil.net/stomp-websocket/doc/) are useful too.

My project source is [here](https://github.com/csleary/wishing-wall/blob/master/client/src/App.js) if you need it.

**Comment by neetogami** [comment]
the problem still persists :/
still no unconfirmed txs though.
I use:
'use strict';
const Stomp = require('stompjs');
const WebSocket = require('ws');
var url = "ws://192.3.61.243:7778/w/messages/websocket";
const socket = new WebSocket(url);

var client = Stomp.over(socket);

client.heartbeat.outgoing = 20000; // client will send heartbeats every 20000ms
client.heartbeat.incoming = 0;     // client does not want to receive heartbeats
                                   // from the server
// Add the following if you need automatic reconnect (delay is in milli seconds)
client.reconnect_delay = 5000;
//client.debug = false;
var _address = "TCNWP3VNMWDQXVSFUPQNH32QN4TLLYH4V2XBAYF7";
//TCXE775AMFC3ZUP3N5SJLVRYONTJFOMUU5PIKLVZ
var connect_callback = function(frame) {
    // called back after the client is connected and authenticated to the STOMP server  

    // Set start date of the monitor
	var date = new Date();
		// Show event
    console.log("Success"); 
	console.log(date.toLocaleString() +': Starting monitor... ');	


    console.log(date.toLocaleString()+': Subscribing to new blocks');
    client.subscribe("/blocks/new", data => {
        date = new Date();
        // Show event
        console.log(date.toLocaleString()+': Received new block');
		const res = JSON.parse(data.body);
		console.log(res);
	});

    // Show event - don't work
    console.log(date.toLocaleString()+': Subscribing to unconfirmed transactions of '+ _address);
	client.subscribe("/unconfirmed/"+_address, data => {
        date = new Date();
        // Show event
        console.log(date.toLocaleString()+': Received unconfirmed transaction');
		const res = JSON.parse(data.body);
		console.log(res);
	});

    // Show event - work
    console.log(date.toLocaleString()+': Subscribing to confirmed transactions of '+ _address);
	client.subscribe("/transactions/"+_address, data => {
        date = new Date();
        // Show event 
        console.log(date.toLocaleString()+': Received confirmed transaction');
		const res = JSON.parse(data.body);
		console.log(res);
	});	
};

client.connect({},connect_callback);

**Comment by csleary** [comment]
True, I can't get unconfirmed transactions to appear on the testnet. They don't work in the official wallet on the testnet either (only confirmed). Given we can't troubleshoot the server code, I think the only way to be able to test this in any capacity would be to run our own nodes to scrutinise error logs.

**Comment by neetogami** [comment]
I got this answer to 1 developer of NEM:
Bloody Rookie:
1. using websockets is not the recommended way for checking unconfirmed transactions, it is too unreliable
2. i recommend using supernodes that have good hardware, e.g. the hugealice servers (those are dedicated servers)
hugealice.nem.ninja
hugealice2.nem.ninja
hugealice3.nem.ninja
hugealice4.nem.ninja


But is not it necessary to have 3M xem for the supernode?

**Comment by csleary** [comment]
You only need the 3M to be paid for _running_ a supernode.

**Comment by neetogami** [comment]
Which socket (host, port) are you using?

**Comment by csleary** [comment]
Just trying in nodejs now, and the sdk seems to work well. I'm using socket.io to send the results to the browser.

Sorry I wasn't clear that I was manually connecting sockets in the browser, not nodejs!

**Comment by neetogami** [comment]
problem solved, last update of this post.
the reason of the problem was that we were connecting to nodes that do not have many resources but if you use using supernodes that have good hardware, e.g. the hugealice servers (those are dedicated servers) then the problems disappear.

what if I do not know what are the dedicated servers for the testnet but
for the mainnet are these:
hugealice.nem.ninja
hugealice2.nem.ninja
hugealice3.nem.ninja
hugealice4.nem.ninja
for the testnet are these(only know it):
bigalice2.nem.ninja

**Comment by csleary** [comment]
Yeah, I've come to realise that it's pretty much down to a node by node basis, as I've had no luck with the hugealices, but alice6 has been sending me uncomfirmed/confirmed transactions via socket quite reliably. So perhaps it's more an issue of the physical routing between nodes and site/app backends, perhaps?

**Comment by neetogami** [comment]
It can be
